apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${NAMESPACE}
  namespace: ${GATEWAY_NAMESPACE}
spec:
  parentRefs:
    - name: istio-ingress
      namespace: ${GATEWAY_NAMESPACE}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: ${BASE_PATH}
      backendRefs:
        - name: ${SERVICE_NAME}
          port: ${SERVICE_PORT}
          namespace: ${NAMESPACE}
